image: fpco/stack-build:latest
stages:
  - build

build-latest:
  stage: build
  script:
    - stack --install-ghc build --test

build-8.0:
  stage: build
  script:
    - stack --stack-yaml stack-8.0.yaml --install-ghc build --test

build-7.10:
  stage: build
  script:
    - stack --stack-yaml stack-7.10.yaml --install-ghc build --test

build-7.8:
  stage: build
  script:
    - stack --stack-yaml stack-7.8.yaml --install-ghc build --test
