.\" Please adjust this date whenever revising the manpage.
.TH OENC 1 2007-10-26 "" ""
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
OENC, ODEC \- encode a binary file, or decode its representation
.SH SYNOPSIS
.B oenc
[\-o file | \-\-output=file]
[\-c codec | \-\-codec=codec]
[file]
.PP
.B odec
[\-o file | \-\-output=file]
[\-c codec | \-\-codec=codec]
[file]
.SH DESCRIPTION
.IR Oenc " and " odec
are used to encode binary files into formats that can be transmitted over
mediums that have limited support for 8-bit data.  An example is SMTP which can
only safely transmit data where the 8th bit is 0.
.SH OPTIONS
.TP
.B \-o file \-\-output=file
Redirect output to file.
.TP
.B \-c codec \-\-codec=codec
Use the indicated codec.  Possible values are
.IR uu ", " b16 "(base16), " b32 "(base32), "
.IR b32h "(base32hex), " b64 "(base64), " b64u (base64url).
By default
.IR oenc " and " odec
uses
.IR uu .
.SH SEE ALSO
.BR uuencode "(1), " compress "(1), " mail "(1), " uucp "(1), " uuencode (5)
.SH AUTHOR
Written by Magnus Therning <magnus@therning.org>.
