resolver: ghc-8.4

packages:
  - '.'

extra-deps:
  - conduit-1.3.0.1
  - exceptions-0.10.0
  - stringsearch-0.3.6.6
  - mono-traversable-1.0.8.1
  - primitive-0.6.3.0
  - resourcet-1.2.0
  - transformers-compat-0.6.0.6
  - unliftio-core-0.1.1.0
  - vector-0.12.0.1
  - hashable-1.2.7.0
  - split-0.2.3.3
  - unordered-containers-0.2.9.0
  - vector-algorithms-0.7.0.1
  - HUnit-1.6.0.0
  - tasty-1.0.1.1
  - tasty-hunit-0.10.0.1
  - tasty-quickcheck-0.10
  - tasty-th-0.1.7
  - QuickCheck-2.11.3
  - ansi-terminal-0.8.0.2
  - async-2.2.1
  - call-stack-0.1.0
  - clock-0.7.2
  - haskell-src-exts-1.20.2
  - optparse-applicative-0.14.2.0
  - random-1.1
  - tagged-0.8.5
  - unbounded-delays-0.1.1.0
  - ansi-wl-pprint-0.6.8.2
  - colour-2.3.4
  - cpphs-1.20.8
  - tf-random-0.5
  - old-locale-1.0.0.7
  - old-time-1.1.0.3
  - polyparse-1.12


flags: {}

extra-package-dbs: []
