resolver: ghc-8.2

packages:
  - '.'

extra-deps:
  - HUnit-1.6.0.0
  - QuickCheck-2.10.0.1
  - ansi-terminal-0.6.3.1
  - ansi-wl-pprint-0.6.7.3
  - async-2.1.1.1
  - call-stack-0.1.0
  - clock-0.7.2
  - conduit-1.3.0
  - cpphs-1.20.8
  - exceptions-0.8.3
  - hashable-1.2.6.1
  - haskell-src-exts-1.19.1
  - lifted-base-0.2.3.11
  - mmorph-1.1.0
  - monad-control-1.0.2.1
  - mono-traversable-1.0.8.1
  - mtl-2.2.1
  - old-locale-1.0.0.7
  - old-time-1.1.0.3
  - optparse-applicative-0.14.0.0
  - parsec-3.1.11
  - polyparse-1.12
  - primitive-0.6.2.0
  - random-1.1
  - regex-base-0.93.2
  - regex-tdfa-1.2.2
  - resourcet-1.2.0
  - split-0.2.3.3
  - stm-2.4.4.1
  - stringsearch-0.3.6.6
  - tagged-0.8.5
  - tasty-0.11.2.3
  - tasty-hunit-0.9.2
  - tasty-quickcheck-0.9.1
  - tasty-th-0.1.7
  - text-1.2.2.2
  - tf-random-0.5
  - transformers-base-0.4.4
  - transformers-compat-0.5.1.4
  - unbounded-delays-0.1.1.0
  - unliftio-core-0.1.1.0
  - unordered-containers-0.2.9.0
  - vector-0.12.0.1
  - vector-algorithms-0.7.0.1

flags: {}

extra-package-dbs: []
