version: 2

jobs:
  build:
    docker:
      - image: nixorg/nix:circleci

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Set up Nix
          command: |
            nix-channel --add https://nixos.org/channels/nixpkgs-unstable
            nix-channel --update
            nix-channel --list
      - run:
          name: Do build
          command: |
            nix-build
