name: sandi
version: 0.4.3
synopsis: Data encoding library
description: >-
  Reasonably fast data encoding library.
maintainer: Magnus Therning <magnus@therning.org>
license: BSD3
category: Codec, Conduit
extra-source-files:
  - package.yaml
  - csrc/*.h

git: https://github.com/magthe/sandi.git

flags:
  with-conduit:
    manual: True
    default: True

library:
  source-dirs:
    - src
  c-sources:
    - csrc/codec.c
  cc-options:
    - -fPIC
    - -Wall
    - -Wextra
  dependencies:
    - base <5
    - bytestring
  when:
    - condition: flag(with-conduit)
      dependencies:
        - conduit
        - exceptions
      exposed-modules:
        - Data.Conduit.Codec.Base16
        - Data.Conduit.Codec.Base32
        - Data.Conduit.Codec.Base32Hex
        - Data.Conduit.Codec.Base64
        - Data.Conduit.Codec.Base64Url
        - Data.Conduit.Codec.Base85
        - Data.Conduit.Codec.QuotedPrintable
        - Data.Conduit.Codec.Uu
        - Data.Conduit.Codec.Xx
        - Data.Conduit.Codec.Yenc
      other-modules:
        - Data.Conduit.Codec.Util

tests:
  sandi-tests:
    source-dirs:
      - test-src
    main: Main.hs
    dependencies:
      - sandi
      - base
      - bytestring
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - tasty-th

benchmarks:
  sandi-bench:
    source-dirs:
      - bench-src
    main: Main.hs
    dependencies:
      - sandi
      - base
      - bytestring
      - criterion
