name: omnicodec
version: 0.8
synopsis: Data encoding and decoding command line utilities
description: >-
  Two simple command line tools built on sandi
  (http://hackage.haskell.org/package/sandi).
maintainer: Magnus Therning <magnus@therning.org>
license: Apache-2.0
license-file: COPYING
category: Codec
extra-source-files:
  - package.yaml

git: https://github.com/magthe/sandi.git

dependencies:
    - base <5
    - cmdargs
    - conduit
    - bytestring
    - sandi
    - transformers

executables:
  odec:
    main: odec.hs
    source-dirs:
      - src
    ghc-options: -Wall

  oenc:
    main: oenc.hs
    source-dirs:
      - src
    ghc-options: -Wall
